### ISSUE TITLE
There is no UInteger32 type for snmp UInt32 type.

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#239]
Checking on SnmpType, there is no native class for UInteger32.  There is an entry in the SNMPType.cs for UInt32 (0x47), but there is no native data type similar to Counter32 or Integer32.

Attached is a possible UInteger32 type (If closely follows Counter32).  TypeCode has been updated to reflect SnmpType.UInt32

**Original Reported Date**: 2011-07-20T11:24:09.72-07:00
**Planned For Release**: 
**Original CodePlex ID**: 7220

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

From http://tools.ietf.org/html/rfc2578#page-8

-- this doesn't wrap
Gauge32 ::=
    [APPLICATION 2]
        IMPLICIT INTEGER (0..4294967295)

-- an unsigned 32-bit quantity
-- indistinguishable from Gauge32
Unsigned32 ::=
    [APPLICATION 2]
        IMPLICIT INTEGER (0..4294967295)

Therefore, there is no need to create a new class for it.


**Original Posted Date**: 2011-07-20T23:37:25.447-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Besides, Unsigned32 is 0x42, not 0x47. http://www.webnms.com/snmp/help/snmpapi/snmpv3/javadocs/com/adventnet/snmp/snmp2/SnmpAPI.html

**Original Posted Date**: 2011-07-20T23:40:58.84-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Just learned that there was an old revision of SNMP where Unsigned32 is a unique type (different from Gauge32), 

http://stackoverflow.com/questions/10756666/what-is-the-correct-encoding-for-snmp-type-unsigned32/10796589#comment14128635_10796589

However, that revision is obsolete. Therefore, #SNMP won't attempt to support that.

**Original Posted Date**: 2012-06-01T05:35:41.4-07:00

**Comment by lextudio-support** [comment]
**Original Closed Date**: 2011-07-21T19:59:34.6-07:00

**Comment by TCVZ** [comment]
I'd like to request this issue be reopened.

The previous comment in October 2024 noted that RFC 1442 is obsolete and replaced by RFC 1902 as the reason to not include UInt32.  Maybe I am reading it incorrectly, but RFC 1902 includes the Unsigned32 data type: https://datatracker.ietf.org/doc/html/rfc1902#section-7.1.11

Additionally, RFC 1902 was obsoleted by RFC 2578 (as of April 1999) which also includes the Unsigned32 data type: https://datatracker.ietf.org/doc/html/rfc2578#section-7.1.11

The details provided are limited, but it is a separate entry from Gauge32 and Integer32/Integer:

> [7.1.11](https://datatracker.ietf.org/doc/html/rfc2578#section-7.1.11).  Unsigned32
>
>   The Unsigned32 type represents integer-valued information between 0
>   and 2^32-1 inclusive (0 to 4294967295 decimal).

Based on [RFC 2570](https://datatracker.ietf.org/doc/html/rfc2570#section-7.1.1), SNMP v3 also uses the same object types and specifically notes Unsigned32 (emphasis is mine):

> STD 58, [RFC 2578](https://datatracker.ietf.org/doc/html/rfc2578) specifies the base data types for the MIB module
>    language, which include: Integer32, enumerated integers, **_Unsigned32_**,
>    Gauge32, Counter32,  Counter64, TimeTicks, INTEGER, OCTET STRING,
>    OBJECT IDENTIFIER, IpAddress, Opaque, and BITS. It also assigns
>    values to several object identifiers.  STD 58, [RFC 2578](https://datatracker.ietf.org/doc/html/rfc2578) further
>    defines the following constructs of the MIB module language:

**Edit:**
Never mind, I didn't realize the underlying encoding of the type was the root issue and made them indistinguishable.
For anyone interested, the actual part that matters: https://datatracker.ietf.org/doc/html/rfc2578#section-2

> -- this wraps
> Counter32 ::=
>     [APPLICATION 1]
>         IMPLICIT INTEGER (0..4294967295)
> 
> -- this doesn't wrap
> Gauge32 ::=
>     [APPLICATION 2]
>         IMPLICIT INTEGER (0..4294967295)
> 
> -- an unsigned 32-bit quantity
> -- indistinguishable from Gauge32
> Unsigned32 ::=
>     [APPLICATION 2]
>         IMPLICIT INTEGER (0..4294967295)

For Gauge32 the [APPLICATION 2] tag means a binary value of 01 to identify it as an APPLICATION specific tag, and 000010 as tag 2.  01000010 = 0x42.  Unsigned32 has the exact same tag of [APPLICATION 2], so there is no difference in the data sent - though the receiving side might have an option to differentiate manually.

It might still be worth having a Unsigned32 object, that is just a derived class of Gauge32 (or vise versa) simply because the RFC lists them individually, plus an Enum can have 2+ items with the same value so it doesn't really create extra effort, but the only real value is to prevent confusion.
This translates to 01 to identify its an APPLICATION tag + 010 to specify the
